name: azure-consulting
version: "1.0"
description: "Standards et prompts Azure pour projets data et intégration"
items:
  instructions:
    - .github/instructions/azure.general.md
    - .github/instructions/azure.terraform.md
    - .github/instructions/azure.adf.md
    - .github/instructions/azure.apim.md
    - .github/instructions/azure.functions.md
    - .github/instructions/azure.security.md
    - .github/instructions/azure.observability.md
  skills:
    - .github/skills/azure/skill-azure-standards.md
    - .github/skills/azure/skill-azure-data.md
    - .github/skills/azure/skill-azure-iac.md
  prompts:
    - .github/prompts/skills/azure-architect.md
    - .github/prompts/skills/azure-dev.md
    - .github/prompts/skills/azure-ba.md
